name: Patch LLVM tree
description: Apply unmerged patches to LLVM tree

inputs:
  patch-path:
    description: Path to be used to clone patches
    required: false
    default: 'patches'
  llvm-path:
    description: Path to be going to clone LLVM
    required: false
    default: 'llvm-project'
  remote-ref:
    description: Explicit pstream ref to be patched
    required: false
    default: ''
  branch-name:
    description: Source patch directory
    required: false
    default: 'main'
  diffs-path:
    description: Path to output diffs after patching
    required: false
    default: 'diffs'

outputs:
  upstream-commit:
    description: Upstream commit hash
    value: ${{ steps.checkout-llvm.outputs.upstream-rev }}

runs:
  using: "composite"
  steps:
    - name: checkout llvm tree
      id: checkout-llvm
      uses: actions/checkout@v5
      with:
        repository: llvm/llvm-project
        fetch-tags: true
        ref: ${{ inputs.remote-ref || inputs.branch-name }}
        path: ${{ inputs.llvm-path }}

    - name: apply patches to ${{ inputs.remote-ref || inputs.branch-name }}
      id: apply-patch
      env:
        INPUTS_PATCH_PATH: ${{ inputs.patch-path }}
        INPUTS_LLVM_PATH: ${{ inputs.llvm-path }}
        INPUTS_BRANCH_NAME: ${{ inputs.branch-name }}
        INPUTS_DIFFS_PATH: ${{ inputs.diffs-path }}
        UPSTREAM_COMMIT: ${{ steps.checkout-llvm.outputs.commit }}
      run: |
        mkdir -p $INPUTS_DIFFS_PATH
        pushd $INPUTS_DIFFS_PATH > /dev/null
        DIFFS_PATH=$PWD
        popd > /dev/null
        pushd $INPUTS_PATCH_PATH > /dev/null
        PATCH_PATH=$PWD
        popd > /dev/null
        cd $INPUTS_LLVM_PATH
        git config user.name github-actions
        git config user.email github@github.com
        git config status.showuntrackedfiles no
        if [ -d "$PATCH_PATH/patches/$INPUTS_BRANCH_NAME" ]; then
          git am --empty=drop $PATCH_PATH/patches/$INPUTS_BRANCH_NAME/*
        fi
        git format-patch -o $DIFFS_PATH $UPSTREAM_COMMIT..HEAD
      shell: bash
