name: Build LLVM
on:
  workflow_call:
    inputs:
      upstream_ref:
        description: "Upstream branch to build"
        type: string
        required: true
        default: "main"
      config:
        description: "Build config script"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: "Upstream branch to build"
        type: string
        required: true
        default: "main"
      config:
        description: "Build config script"
        type: string
        required: true
        default: "clang-dylib"

jobs:
  do_build:
    runs-on: windows-latest
    name: Build LLVM ${{ inputs.upstream_ref }} ${{ inputs.config }}
    concurrency:
      group: build-self-cygwin

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-patch
        uses: actions/checkout@v5
        with:
          path: patches

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./patches/.github/actions/prepare-cygwin-root

      - name: prepare llvm tree
        id: prepare-tree
        uses: ./patches/.github/actions/patch-llvm
        with:
          remote-ref: ${{ inputs.upstream_ref }}

      - name: build llvm
        id: build-llvm
        uses: ./patches/.github/actions/build-llvm
        env:
          LIT_OPTS: '--show-suites'
        with:
          config-name: ${{ inputs.config }}
          parallel-compile-jobs: 3
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-target: 'check'

      - name: check llvm
        timeout-minutes: 180
        env:
          BUILD_NAME: ${{ steps.build-llvm.outputs.build-name }}
        run: |
          export LIT_OPTS="-q --no-execute --ignore-fail --xunit-xml-output=$PWD/dryrun-$BUILD_NAME.xml"
          cmake --build build-$BUILD_NAME -- check
          export LIT_OPTS="-sv --xunit-xml-output=$PWD/result-$BUILD_NAME.xml"
          cmake --build build-$BUILD_NAME -- check
        shell: cygwin-bash '{0}'

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-log
          overwrite: true
          path: ${{ github.workspace }}/*-${{ steps.build-llvm.outputs.build-name }}.xml
