name: Construct Cygwin Filesystem
on:
  workflow_dispatch:

jobs:
  do-update:
    runs-on: windows-latest
    concurrency:
      group: construct-cygwin

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: update Cygwin
        uses: ./.github/actions/prepare-cygwin-root
        with:
          skip-update: false
