name: Construct Cygwin Filesystem
on:
  workflow_dispatch:

jobs:
  do-update:
    runs-on: windows-latest

    steps:
      - name: prepare patches
        uses: actions/checkout@v5
        with:
          path: patches
      - name: update Cygwin
        uses: ./patches/.github/actions/prepare-cygwin-root
        with:
          skip-update: false
