name: Build Scheduler
on:
  schedule:
    - cron: '18 15 * * *'
    - cron: '18 21 * * *'
    - cron: '18 3 * * *'
    - cron: '18 9 * * *'

jobs:
  call-build-clang-static:
    if: github.event.schedule == '18 15 * * *'
    name: Schedule build clang-static
    uses: ./.github/workflows/build_llvm.yml
    with:
      upstream-branch: 'main'
      patch-series: 'main'
      config: 'clang-static'

  call-build-clang-dylib:
    if: github.event.schedule == '18 3 * * *'
    name: Schedule build clang-dylib
    uses: ./.github/workflows/build_llvm.yml
    with:
      upstream-branch: 'main'
      patch-series: 'main'
      config: 'clang-dylib'

  call-build-cross-clang-static:
    if: github.event.schedule == '18 21 * * *'
    name: Schedule build cross-clang-static
    uses: ./.github/workflows/build_cross_llvm.yml
    with:
      upstream-branch: 'main'
      patch-series: 'cross'
      config: 'cross-clang-static'

  call-build-cross-clang-dylib:
    if: github.event.schedule == '18 9 * * *'
    name: Schedule build cross-clang-dylib
    uses: ./.github/workflows/build_cross_llvm.yml
    with:
      upstream-branch: 'main'
      patch-series: 'cross'
      config: 'cross-clang-dylib'
