name: Use Cygwin Filesystem
on:
  workflow_dispatch:

jobs:
  do_build:
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - run: git config --global core.autocrlf input
      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key: cygwin-rootfs-
          restore-keys: |
            cygwin-rootfs-
          path: |
            cygwinroot.tar.gz
            minimal_tar
      - name: unpack Cygwin
        run: |
          move cygwinroot.tar.gz minimal_tar
          cd minimal_tar
          path %cd%\bin;%path%
          bin\tar.exe xf cygwinroot.tar.gz
          del /f cygwinroot.tar.gz
        shell: cmd
      - name: check cygwin
        run: |
          export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
          export GITHUB_WORKSPACE="$(cygpath -u '${{github.workspace}}')"
          cd "$GITHUB_WORKSPACE"
          pwd
          ls
          ls /
          ls /usr
        shell: d:\cygwin\bin\bash.exe -leo pipefail -o igncr '{0}'

