name: Test Check LLVM
on:
  workflow_dispatch:
    inputs:
      upstream-branch:
        description: 'Upstream branch to build'
        type: string
        required: false
        default: 'main'
      patch-series:
        description: 'Patch series to apply'
        type: string
        required: false
        default: 'main'
      config:
        description: 'Build config script'
        type: string
        required: false
        default: 'clang-dylib'

jobs:
  select:
    runs-on: ubuntu-latest
    name: Select target
    outputs:
      upstream-branch: ${{ inputs.upstream-branch || 'main' }}
      patch-series: ${{ inputs.patch-series || inputs.upstream-branch || 'main' }}
      config: ${{ inputs.config || steps.selector.outputs.config || 'clang-dylib' }}

    steps:
      - id: selector
        env:
          SCHEDULE: ${{ github.event.schedule }}
        run: |
          case "$SCHEDULE" in
            '18 15 * * *')
              echo config=clang-static >> "$GITHUB_OUTPUT"
              ;;
            '18 3 * * *')
              echo config=clang-dylib >> "$GITHUB_OUTPUT"
              ;;
            '')
              ;;
            *)
              false
              ;;
          esac
        shell: bash

  check:
    permissions: read-all
    runs-on: windows-latest
    needs: select
    name: Check LLVM ${{ needs.select.outputs.upstream-branch }} ${{ needs.select.outputs.config }}
    concurrency:
      group: test-self-cygwin-test

    steps:
      - run: git config --global core.autocrlf input

      - uses: actions/download-artifact@v5
        with:
          run-id: '18085127686'
          name: 'build-artifact'
          github-token: ${{ github.token }}
          #repository: ${{ github.repository }}

      - name: prepare patches
        id: checkout-patch
        uses: actions/checkout@v5
        with:
          path: patches
          ref: 'main'

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./patches/.github/actions/prepare-cygwin-root

      - name: prepare llvm tree
        id: prepare-tree
        uses: ./patches/.github/actions/patch-llvm
        with:
          patch-series: ${{ needs.select.outputs.patch-series }}
          remote-ref: 'cac0635ee9e947b5f90130df2f471aa4b722e04b'

      - name: check llvm
        env:
          BUILD_NAME: 'clang-dylib-cac0635ee+mod-6da8939'
          CONFIG: ${{ needs.select.outputs.config }}
          CYGWINROOT: ${{ steps.prepare-cygwin.outputs.root }}
          TIMEOUT: '5m'
        run: ./patches/scripts/runtest.sh
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-log
          overwrite: true
          path: |
            ${{ github.workspace }}/*-clang-dylib-cac0635ee+mod-6da8939.xml
            ${{ github.workspace }}/*-clang-dylib-cac0635ee+mod-6da8939.txt
