name: Use Cygwin Filesystem
on:
  workflow_dispatch:

jobs:
  do_build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: update Cygwin
        id: cygwin
        uses: ./.github/actions/prepare-cygwin-root
        with:
          install-dir: 'd:\thecygwin'
          cache-key-base: 'key'

      - name: check cygwin
        run: |
          echo ${{ steps.cygwin.outputs.root }}
          echo ${{ steps.cygwin.outputs.workspace }}
        shell: cmd

      - name: check cygwin
        run: |
          echo ${{ steps.cygwin.outputs.root }}
          echo ${{ steps.cygwin.outputs.workspace }}
          ls
          ls /
          ls /usr
          mount
        shell: cygwin-bash '{0}'
