name: Use Cygwin Sysroot from Linux
on:
  workflow_dispatch:

jobs:
  do_build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: update Cygwin
        id: cygwin
        uses: ./.github/actions/prepare-cygwin-root
      - name: check cygwin
        run: |
          echo ${{ steps.cygwin.outputs.root }}
          echo ${{ steps.cygwin.outputs.workspace }}
          ls
          ls ${{ steps.cygwin.outputs.root }}
        shell: bash
