name: Use Cygwin Sysroot from Linux
on:
  workflow_dispatch:

jobs:
  do_build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: update Cygwin
        uses: ./.github/actions/prepare-cygwin-root
        with:
          install-dir: 'd:\thecygwin'
          cache-key-base: 'key'

      - name: check cygwin
        run: |
          echo ${{ steps.cygwin.outputs.root }}
          echo ${{ steps.cygwin.outputs.workspace }}
          ls
          ls thecygwin
        shell: bash
